version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

#  graphql-service:
#    build:
#      context: ..
#      dockerfile: Dockerfile
#    container_name: graphql-service
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/mydatabase
#    depends_on:
#      - mongodb

volumes:
  mongo-data: